// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://jjsgcsalrxypwhnqtxkz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Impqc2djc2Fscnh5cHdobnF0eGt6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU1NTE4MTksImV4cCI6MjA3MTEyNzgxOX0.1yiYw48MzZ5Tikkcw6dyKZQ-YgSmf-D8WCh9GQ9cwsQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);